---
jobs:
  - name: echo-job
    plan:
      - task: echo-something
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 1.35.0
          run:
            path: echo
            args:
              - ((msg))
