---
jobs:
  - name: hello-world-job
    plan:
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 1.35.0
          run:
            path: echo
            args:
              - Hello world!
