---
resources:
  - name: simple-python-repo
    type: git
    icon: github
    source:
      uri: git@github.com:jiabh/simple-python.git
      branch: master
      private_key: ((github-pri-key))

jobs:
  - name: run-program
    plan:
      - get: simple-python-repo
        trigger: true

      - task: start-program
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: 3.9.15-slim
          inputs:
            - name: simple-python-repo
          run:
            path: sh
            args:
              - -c
              - |
                cd simple-python-repo/
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python main.py

  - name: echo-hello-world
    plan:
      - get: simple-python-repo
        passed: [ run-program ]
        trigger: true

      - task: echo
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 1.35.0
          run:
            path: sh
            args:
              - -c
              - |
                echo Hello world!
